name: shopping_app
description: This is a e-commerce shopping app .
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_image_slideshow: ^0.1.4
#  carousel_pro: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
#     - assets/images/fusionlogo.png
     - assets/images/categories/
     - assets/images/home/top/
     - assets/images/home/top2/
     - assets/images/home/top3/
     - assets/images/home/top4/
     - assets/images/home/shirt/
     - assets/images/home/tshirt/
     - assets/images/account/
     - assets/images/home/accesseries/
     - assets/images/home/bedsheet/
     - assets/images/home/beautykit/
     - assets/images/home/girldress/
     - assets/images/home/girlkurti/
     - assets/images/home/shoes/
     - assets/images/home/winterwear/
     - assets/images/jewellery/


  fonts:
     - family: Mulish
       fonts:
         - asset: assets/fonts/Mulish-Regular.ttf
         - asset: assets/fonts/Mulish-Bold.ttf
         - asset: assets/fonts/Mulish-Black.ttf
         - asset: assets/fonts/Mulish-Italic.ttf
         - asset: assets/fonts/Mulish-Medium.ttf
         - asset: assets/fonts/Mulish-SemiBold.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
